---
title: "Homework 5"
author: "Ford Holland"
date: "11/2/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(viridis)
library(p8105.datasets)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```

## Problem 1

Function to replace missing values in numeric and character vectors.

```{r}
replace_na = function(x) {
  if (!(is.numeric(x) | is.character(x))) {
    stop("This function only supports numeric and character arguments.")
  } else if (is.numeric(x)) {
    x = replace(x, is.na(x), mean(x, na.rm = TRUE)) %>% 
      round(1)
    return(x)
  } else if (is.character(x)) {
    x = replace(x, is.na(x), "virginica")
    return(x)
  }
}
```

Apply this function to the columns of `iris_with_missing` using a map statement.

```{r}
iris_imputed = map_df(.x = iris_with_missing, ~replace_na(.x))
```






























